#!/bin/bash
# =============================================================================
# HRIS VPS First-Time Setup Script
# =============================================================================
# Usage:
#   1. Copy this script to your VPS
#   2. chmod +x setup-vps.sh
#   3. ./setup-vps.sh
#
# This script will:
#   - Install Docker + Docker Compose (if not installed)
#   - Clone the repository
#   - Generate secure .env
#   - Setup firewall (UFW)
#   - Start the application
#   - Optionally setup nginx + SSL
# =============================================================================

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}"
echo "╔══════════════════════════════════════════════════════╗"
echo "║       HRIS Production VPS Setup                     ║"
echo "╚══════════════════════════════════════════════════════╝"
echo -e "${NC}"

# =============================================================================
# Configuration - CHANGE THESE
# =============================================================================
REPO_URL="${REPO_URL:-https://github.com/YOUR_USER/hris-management-system.git}"
APP_DIR="${APP_DIR:-$HOME/hris-prod}"
DOMAIN="${DOMAIN:-}"  # e.g. hris.yourdomain.com
SETUP_NGINX="${SETUP_NGINX:-no}"  # Set to "yes" to enable nginx reverse proxy

# =============================================================================
# 1. Install Docker
# =============================================================================
install_docker() {
    if command -v docker &> /dev/null; then
        echo -e "${GREEN}✅ Docker already installed: $(docker --version)${NC}"
        return
    fi

    echo -e "${YELLOW}📦 Installing Docker...${NC}"
    curl -fsSL https://get.docker.com | sh
    sudo usermod -aG docker "$USER"
    sudo systemctl enable docker
    sudo systemctl start docker
    echo -e "${GREEN}✅ Docker installed${NC}"
}

# =============================================================================
# 2. Clone repository
# =============================================================================
clone_repo() {
    if [ -d "$APP_DIR/.git" ]; then
        echo -e "${GREEN}✅ Repository exists, pulling latest...${NC}"
        cd "$APP_DIR"
        git fetch origin
        git reset --hard origin/main
    else
        echo -e "${YELLOW}📦 Cloning repository...${NC}"
        mkdir -p "$APP_DIR"
        git clone "$REPO_URL" "$APP_DIR"
        cd "$APP_DIR"
    fi
}

# =============================================================================
# 3. Generate secure .env
# =============================================================================
generate_env() {
    if [ -f "$APP_DIR/.env" ]; then
        echo -e "${YELLOW}⚠️  .env already exists. Overwrite? [y/N]${NC}"
        read -r OVERWRITE
        if [ "$OVERWRITE" != "y" ] && [ "$OVERWRITE" != "Y" ]; then
            echo -e "${GREEN}✅ Keeping existing .env${NC}"
            return
        fi
    fi

    echo -e "${YELLOW}🔐 Generating secure secrets...${NC}"
    DB_PASSWORD=$(openssl rand -base64 24)
    JWT_SECRET=$(openssl rand -base64 48)

    cat > "$APP_DIR/.env" << ENVEOF
# Generated by setup-vps.sh on $(date)
DB_PASSWORD=$DB_PASSWORD
DB_NAME=hris_db
DB_HOST=mysql
DB_PORT=3306
DB_USER=root
JWT_SECRET=$JWT_SECRET
PORT=5000
NODE_ENV=production
ENVEOF

    chmod 600 "$APP_DIR/.env"
    echo -e "${GREEN}✅ .env generated with secure secrets${NC}"
    echo -e "${CYAN}   DB_PASSWORD: $DB_PASSWORD${NC}"
    echo -e "${CYAN}   JWT_SECRET:  $JWT_SECRET${NC}"
    echo -e "${YELLOW}   📋 Save these! You'll need them for GitHub Secrets.${NC}"
}

# =============================================================================
# 4. Setup firewall
# =============================================================================
setup_firewall() {
    if ! command -v ufw &> /dev/null; then
        echo -e "${YELLOW}⚠️  UFW not installed, skipping firewall${NC}"
        return
    fi

    echo -e "${YELLOW}🔥 Configuring firewall...${NC}"
    sudo ufw allow 22/tcp    # SSH
    sudo ufw allow 80/tcp    # HTTP
    sudo ufw allow 443/tcp   # HTTPS
    sudo ufw --force enable
    echo -e "${GREEN}✅ Firewall configured${NC}"
}

# =============================================================================
# 5. Setup nginx + SSL (optional)
# =============================================================================
setup_nginx() {
    if [ "$SETUP_NGINX" != "yes" ]; then
        echo -e "${YELLOW}⏭️  Skipping nginx setup (SETUP_NGINX=no)${NC}"
        return
    fi

    if [ -z "$DOMAIN" ]; then
        echo -e "${RED}❌ DOMAIN not set. Cannot setup SSL.${NC}"
        echo -e "${YELLOW}   Set DOMAIN=yourdomain.com and re-run.${NC}"
        return
    fi

    echo -e "${YELLOW}🌐 Setting up nginx + SSL for $DOMAIN...${NC}"

    # Install nginx
    sudo apt update && sudo apt install -y nginx certbot python3-certbot-nginx

    # Copy nginx config
    sudo cp "$APP_DIR/nginx/nginx.conf" /etc/nginx/nginx.conf

    # Test config
    sudo nginx -t && sudo systemctl reload nginx

    # Obtain SSL certificate
    sudo certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos --email "admin@$DOMAIN"

    # Auto-renewal
    echo "0 3 * * * certbot renew --quiet" | sudo crontab -

    echo -e "${GREEN}✅ nginx + SSL configured${NC}"
}

# =============================================================================
# 6. Start application
# =============================================================================
start_app() {
    echo -e "${YELLOW}🚀 Starting HRIS...${NC}"
    cd "$APP_DIR"

    # Create backup directory
    mkdir -p backups

    # Build and start
    docker compose build web
    docker compose up -d --remove-orphans

    # Wait for health
    echo -e "${YELLOW}⏳ Waiting for application to be healthy...${NC}"
    for i in $(seq 1 30); do
        if curl -sf http://localhost:5000/health > /dev/null 2>&1; then
            echo -e "${GREEN}✅ Application is healthy!${NC}"
            break
        fi
        sleep 2
    done

    # Show status
    echo ""
    docker compose ps
    echo ""
    docker compose logs web --tail 10
}

# =============================================================================
# 7. Print summary
# =============================================================================
print_summary() {
    echo ""
    echo -e "${GREEN}╔══════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║       HRIS Setup Complete! 🎉                       ║${NC}"
    echo -e "${GREEN}╚══════════════════════════════════════════════════════╝${NC}"
    echo ""

    # Detect public IP
    PUBLIC_IP=$(curl -s ifconfig.me 2>/dev/null || echo "YOUR_VPS_IP")

    echo -e "${CYAN}📋 Quick Info:${NC}"
    echo "   URL:      http://$PUBLIC_IP:5000"
    if [ -n "$DOMAIN" ]; then
        echo "   Domain:   https://$DOMAIN"
    fi
    echo "   Login:    ADM001 / admin123"
    echo ""
    echo -e "${CYAN}📋 Management Commands:${NC}"
    echo "   docker compose ps              # View status"
    echo "   docker compose logs -f web     # View logs"
    echo "   docker compose restart web     # Restart web"
    echo "   docker compose down            # Stop"
    echo "   docker compose up -d           # Start"
    echo ""
    echo -e "${CYAN}📋 Next Steps:${NC}"
    echo "   1. Change admin password after first login"
    echo "   2. Add secrets to GitHub (Settings → Secrets → Actions):"
    echo "      - SSH_KEY:        Your VPS private SSH key"
    echo "      - SSH_USER:       Your VPS username"
    echo "      - STAGING_IP:     Staging server IP"
    echo "      - PROD_IP:         Production server IP"
    echo "      - PROD_DOMAIN:    Production domain"
    echo "      - DB_PASSWORD_STAGING:  (from .env on staging)"
    echo "      - JWT_SECRET_STAGING:   (from .env on staging)"
    echo "      - DB_PASSWORD_PROD:     (from .env above)"
    echo "      - JWT_SECRET_PROD:      (from .env above)"
    echo "   3. Setup SSL: SETUP_NGINX=yes DOMAIN=yourdomain.com ./setup-vps.sh"
    echo "   4. Setup automatic backups:"
    echo "      crontab -e"
    echo "      0 2 * * * cd ~/hris-prod && ./scripts/backup-db.sh"
    echo ""
}

# =============================================================================
# Main
# =============================================================================
main() {
    install_docker
    clone_repo
    generate_env
    setup_firewall
    setup_nginx
    start_app
    print_summary
}

main
